[tox]
envlist = py39,py310,py311,py312,py313,py314,py313t,py314t

[testenv]
deps=
    -r{toxinidir}/requirements-test.txt
commands=
    pytest

# Do not export PYTHON_GIL=0 as environment variable before running tox,
# that variable is applied to the Python interpreter that launches tox
# and not tests. It may cause tox to fail with an error like this:
#   Fatal Python error: config_read_gil: Disabling the GIL is not supported by this build                                                                                                                                                  
#   Python runtime state: preinitialized 
[testenv:py313t,py314t]
setenv =
    # Enforce that the GIL is disabled. In case some dependency
    # tries to silently turn the GIL back on.
    PYTHON_GIL = 0
